if Rails.env.production?
  DISQUS_SECRET_KEY = 'ZIfe5LCHZ6VK920YUj2LIVEt4H5T8CfPhC1j75ikovOkPnNGLIUJDuNfsZ9cX8TG'
  DISQUS_PUBLIC_KEY = 'NlGHyHyNqFFp2zcXh0kJvPOJV54hoUTw5os3bS1hefUoshcwvp1Lq8pdR3xu8xML'
  DISQUS_FORUM = 'savitri'
else
  DISQUS_SECRET_KEY = 'UbgW031em0aUViTMNM6Jifmv7h1ToyE7TbtHu9CGqQdfwMp4EnijWKk7zLMnnQsy'
  DISQUS_PUBLIC_KEY = 'WKs4u4QN3TBZlhCRVSQoXRZXiFbA7m4DgmPN3NIdPKmmH6lezPyFPxO8BNlUNmez'
  DISQUS_FORUM = 'sagarjunnarkargithubio'
end
